### ISSUE TITLE
it should but it doenst

### ISSUE THREAD

**Issue by FlareFlo** [conradludgate/linked_list_rs#5]
fix ASAP

**Comment by conradludgate** [comment]
Please describe your problem and a code sample of what you tried. Thanks

**Comment by Noratrieb** [comment]
I might be a bit overreacting here, but I seriously think that this response is unacceptable.
This user is desperately asking for a fix, and you chose to deny this fix and want to see their code, probably to make fun of it, instead. This is not only a violation of the basic principles of privacy but also mockery.
I would strongly urge you to step down as a maintainer, or at the very least, apologize.

**Comment by conradludgate** [comment]
Why are you booing me I'm right

**Comment by conradludgate** [comment]
I was quoting the bible... If I can't even do that I don't know what you want from me

**Comment by FlareFlo** [comment]
"Please describe your problem and a code sample of what you tried. Thanks" Jesus said
psalm 69:420

**Comment by Noratrieb** [comment]
:/

**Comment by Noratrieb** [comment]
I will fix it now.
